language: cpp
dist: trusty

branches:
  only:
  - master

"compiler": "clang++",

git:
  depth: 1

os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
      packages:
        - clang-7
        - libstdc++-7-dev
  env:
    - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install flex
  - sudo apt-get install bison

script:
  - make test
  - make draw