language: cpp

matrix:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7.0
          packages:
            - clang-7.0
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

before_install:
    - eval "${MATRIX_EVAL}"

branches:
  only:
  - master

git:
  depth: 1

compiler: clang

install:
- sudo apt-get install flex
- sudo apt-get install bison
script:
  - clang++ --version
  - make

