language: cpp
compiler: gcc
dist: trusty

branches:
  only:
  - master

git:
  depth: 1

addons:
  apt:
    sources:
    # Clang 7:
      - llvm-toolchain-trusty-7
      - ubuntu-toolchain-r-test
    packages:
      - clang-7
env:
  - MATRIX_EVAL="CC=clang-7.0 && CXX=clang-7.0"

before_install:
- eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install flex
  - sudo apt-get install bison

script:
  - make test
  - make draw