language: cpp
compiler: gcc
dist: trusty

branches:
  only:
  - master

git:
  depth: 1

addons:
  apt:
    sources:
    # Clang 7:
      - llvm-toolchain-trusty-7
      - ubuntu-toolchain-r-test
    packages:
      - clang-7

install:
  - sudo apt-get install flex
  - sudo apt-get install bison

script:
  - make test
  - make draw