#pragma once

#include "../irt/node/binary-operator.hpp"
#include "../irt/node/call.hpp"
#include "../irt/node/conditional-jump.hpp"
#include "../irt/node/constant.hpp"
#include "../irt/node/expression.hpp"
#include "../irt/node/expression-sequence.hpp"
#include "../irt/node/jump.hpp"
#include "../irt/node/label.hpp"
#include "../irt/node/memory.hpp"
#include "../irt/node/move.hpp"
#include "../irt/node/name.hpp"
#include "../irt/node/node.hpp"
#include "../irt/node/statement.hpp"
#include "../irt/node/statement-sequence.hpp"
#include "../irt/node/temporary.hpp"
#include "../irt/node/void.hpp"
