#pragma once

#include "../ir-tree/ir-binary-operator.hpp"
#include "../ir-tree/ir-call.hpp"
#include "../ir-tree/ir-conditional-jump.hpp"
#include "../ir-tree/ir-constant.hpp"
#include "../ir-tree/ir-expression.hpp"
#include "../ir-tree/ir-jump.hpp"
#include "../ir-tree/ir-label.hpp"
#include "../ir-tree/ir-memory.hpp"
#include "../ir-tree/ir-move.hpp"
#include "../ir-tree/ir-name.hpp"
#include "../ir-tree/ir-node.hpp"
#include "../ir-tree/ir-sequence.hpp"
#include "../ir-tree/ir-statement.hpp"
#include "../ir-tree/ir-temporary.hpp"
