#pragma once

#include "../irt/node/ir-binary-operator.hpp"
#include "../irt/node/ir-call.hpp"
#include "../irt/node/ir-conditional-jump.hpp"
#include "../irt/node/ir-constant.hpp"
#include "../irt/node/ir-expression.hpp"
#include "../irt/node/ir-jump.hpp"
#include "../irt/node/ir-label.hpp"
#include "../irt/node/ir-memory.hpp"
#include "../irt/node/ir-move.hpp"
#include "../irt/node/ir-name.hpp"
#include "../irt/node/ir-node.hpp"
#include "../irt/node/ir-sequence.hpp"
#include "../irt/node/ir-statement.hpp"
#include "../irt/node/ir-temporary.hpp"
